### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by gradyrobbins** [alagrad94/stevesgitdata#1]
Russell i relied on your code a lot when i was working through this exercise.  Thank you.

I have a question about your approach to requirement #6.  
i see you declared, but did not use:  
``` 
var repoName6 = githubData[i].repo.name;
```
it's not an "issue" per se, since the correct result is console.logged.  I wanted to find a way to leave constructive criticism your code without submitting a PR and am trying out this "issues" tab.  

thanks,
Grady

**Comment by alagrad94** [comment]
You're right.  I made the variable because I thought I was going to need it to identify the coding languages.  I ended up not needing it and forgot to delete it.
